### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by radutopala**

### CODE REVIEW

**Comment by radutopala** [comment]
@kazupon it's a new Slack community around VueJs, called Vuers. A lot of devs are using Slack these days, installed locally on their desktops and phones, which means fast access to the chat. The community signup is based on invitation.

**Comment by aristidesfl** [comment]
@radutopala what does this slack "community" add, that you can't get from the existing Vue slack team?

----------------------------
*Rant:* Just what we needed. Yet another slack "community". People used to create channels. Now they create communities with 5+ channels instead.
slack sucks

**Comment by aristidesfl** [comment]
https://vueslack.com/

**Comment by radutopala** [comment]
Great, didn't know about it, let's use that :)

**Pull request closed without merging**
