### PR TITLE
added VueFront

### PR DESCRIPTION
**Pull request by dmitriyzhuk**
added VueFront - CMS Agnostic PWA & SPA.
- to Open Source category.

### CODE REVIEW

**Comment by LinusBorg** [comment]
Please resolve the conflicts :)

**Comment by dmitriyzhuk** [comment]
Guys, I did this yesterday and now  Iam not able to resolve the conflict. Telling be I don't have write access to this PR. really strange... Maybe I am doing this wrong. all I am adding just one line of text. 
Should I do another PR?

**Comment by Scrum** [comment]
@dmitriyzhuk For my part, there is also no such opportunity, it’s better to make a new one

**Comment by dmitriyzhuk** [comment]
Ok, just made this one https://github.com/vuejs/awesome-vue/pull/3227. you can close this PR 

thank you!

**Pull request closed without merging**
