### PR TITLE
Added Particles.vue3 (The VueJS 3.x component for particles backgrounds)

### PR DESCRIPTION
**Pull request by matteobruni**
- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [ ] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [x] Link description does not contain a link to an author / third-party resource
- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

#### `Apps/Websites`

- [ ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [ ] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vue, provided that guests could reasonably check out how Vue was used A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

### CODE REVIEW

**Comment by matteobruni** [comment]
I have updated the description of Particles.vue specifying that is 2.x compatible, it's another library of the same project that I'm maintaining. I just say it to avoid any kind of problem with that update.

**Comment by Scrum** [comment]
I think it is worth pointing out directly in the documentation https://github.com/matteobruni/tsparticles.

I don’t think it’s a good idea to link to different versions of the same product.

@LinusBorg What do you think about this ?

**Comment by matteobruni** [comment]
Maybe a single line like

- tsParticles - Blah blah blah (Vue.js 2.x and Vue.js 3.x packages available)

Could be a better solution?

**Comment by Scrum** [comment]
> Maybe a single line like
> 
>     * tsParticles - Blah blah blah (Vue.js 2.x and Vue.js 3.x packages available)
> 
> 
> Could be a better solution?

This is permissible within the rules. But again, I think that the package documentation should have all the necessary information for the user / developer.

**Comment by matteobruni** [comment]
The package documentation has all these informations, but the repository has not only Vue components.
If it's fine I can just replace the Particles.vue readme links with tsParticles readme (the main repo readme)

**Comment by Scrum** [comment]
> The package documentation has all these informations, but the repository has not only Vue components.
> If it's fine I can just replace the Particles.vue readme links with tsParticles readme (the main repo readme)

👍

**Comment by matteobruni** [comment]
Fixed, hope it's good now

**Review by Scrum — APPROVED** [review]

**Pull request merged**
