### PR TITLE
clean latest PRs and add brillout/awesome-vue-refactor PRs

### PR DESCRIPTION
**Pull request by brillout**
@adeptoas
@moip
@olefirenko
@qurateinc
@keuller
@christianmalek
@superwf

Would be great to state v2 support in the readme or repo description.

<br/>
<br/>

@JiriChara `vue-gravatar`'s readme doesn't exactly explain what this library does and a live demo would be nice.

<br/>

@zack24q The readme should be in English.

<br/>

@JetBrains All libraries on the list have a readme, would be good if this plugin does have one as well.

<br/>
<br/>

@jcc
@waynecz
@shershen08

The only reason of removing your library from Awesome Vue is to make the list more useful.
As stated in the last comment at https://github.com/brillout/awesome-vue-refactor/issues/6#issuecomment-286596766 please create an issue at brillout/awesome-vue-refactor to discuss whether your library should be part of the list or not.
I'm open to discuss what should or shouldn't be added to the list.
Obviously re-adding your libraries beyond my back won't do you a favor though.

### CODE REVIEW

**Comment by olefirenko** [comment]
@brillout Done

**Comment by christianmalek** [comment]
@brillout Done. (It's for Vuex 2.x, the Vue version isn't important.)

**Comment by JiriChara** [comment]
@brillout I have added a demo to the README of vue-gravatar: https://jirichara.github.io/vue-gravatar/

**Comment by superwf** [comment]
@brillout vue version description added

**Comment by zack24q** [comment]
@brillout english readme added

**Pull request closed without merging**
