### PR TITLE
Added v-ajax-form

### PR DESCRIPTION
**Pull request by hosokawat**
This adds v-ajax-form to the UI Utilities > Miscellaneous section. It meets all the guidelines as listed in the CONTRIBUTING.md

### CODE REVIEW

**Comment by LinusBorg** [comment]
there's english docs linked to at the beginning of the README, that's ok I think.

**Comment by Scrum** [comment]
@hosokawat Maybe you should ask the author to make it like `primary`

**Comment by hosokawat** [comment]
I changed English to be primary.

**Comment by hosokawat** [comment]
thank to everyone!

**Pull request merged**
