### PR TITLE
Add Bayo (v2.bayo.vn) website

### PR DESCRIPTION
**Pull request by imcvampire**

### CODE REVIEW

**Comment by DannyFeliz** [comment]
The site is down

**Comment by kazupon** [comment]
I seem that it is live.

**Comment by imcvampire** [comment]
Yeah, It's up now. I think we have a small issue with DNS.

**Comment by kazupon** [comment]
Thanks :)
Can you resolve the conflict please?
We can not merge your PR.  😉

**Comment by imcvampire** [comment]
OK It's done now.

**Comment by kazupon** [comment]
Thanks!!

**Pull request merged**
