### PR TITLE
add mini-vue

### PR DESCRIPTION
**Pull request by cuixiaorui**
This library strips the core logic from the vue3 source code, leaving only the core logic for everyone to learn. With detailed Chinese comments and complete output to help users understand the run-time process.

### CODE REVIEW

**Review by Scrum — CHANGES_REQUESTED** [review]
## Checklist

- [x] git: pull request template structure not broken
- [x] git: pull request template not selected `type`
- [x] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [ ] git: broken PR
- [ ] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [ ] lists: not the last on the list
- [ ] docs: no documentation
- [x] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md)

**Comment by cuixiaorui** [comment]
Hello. I'm a little confused

README Is it required in English？

**Comment by Scrum** [comment]
> README Is it required in English？

yes

**Comment by cuixiaorui** [comment]
I will resubmit a conform to the specifications of pr

**Pull request closed without merging**
