### PR TITLE
Add vue-wysiwyg

### PR DESCRIPTION
**Pull request by chmln**
Adds [vue-wysiwyg](https://github.com/chmln/vue-wysiwyg) to the list of rich text editors.

### CODE REVIEW

**Comment by michgeek** [comment]
Is this still in alpha?

**Comment by chmln** [comment]
@michgeek not anymore. just forgot to update the screenshot

**Comment by Piterden** [comment]
Could you make a demo?

**Comment by chmln** [comment]
@piterden absolutely

**Pull request merged**
