### PR TITLE
Adding vue-notification-system to notifications

### PR DESCRIPTION
**Pull request by javimendezona**
- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [ ] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [ ] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [ ] The documentation is in English.
- [ ] The project is active and maintained.
- [ ] The project accepts contributions.
- [ ] Not a commercial product

#### `Apps/Websites`

- [x] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [x] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [x] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vue, provided that guests could reasonably check out how Vue was used A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

### CODE REVIEW

**Comment by javimendezona** [comment]
This component isn't open source. Should it go in a different section?

**Comment by Scrum** [comment]
> This component isn't open source. Should it go in a different section?

The company will not be able to make suggestions or leave error messages for your product

**Comment by javimendezona** [comment]
I'm not sure i understand. There is no public repository to link to. Is that required to be added to this list? The NPM package is public which is why I linked that instead. Let me know what I should change. Thanks!

**Comment by spekulatius** [comment]
Hey @javimendezona 

just jumping in as I've been a bit surprised about the package size: It's 21.2 MB according to the NPM page? That's quite a lot - roughly seven times the size of Vue tiself. What is making it so large?

Cheers,
Peter

**Comment by javimendezona** [comment]
Hmm that's a good point. I must have done something wrong with the vue build in terms of the dependencies.  I'm relatively new to publishing to npm so I probably did something wrong there. I'll take a look at it. Thanks

**Comment by spekulatius** [comment]
I'm no expert in this, but I've had a look brief look and seen some webpack stuff - I guess that doesn't need to be in. Just the pure code.

**Comment by Scrum** [comment]
> I'm not sure i understand. There is no public repository to link to. Is that required to be added to this list? The NPM package is public which is why I linked that instead. Let me know what I should change. Thanks!

the rules [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md)

**Comment by javimendezona** [comment]
@spekulatius I updated the npm package after rebuilding with different build settings which brought the size down. Sorry for the long delay, just had some big personal life changes in the last couple months

**Comment by spekulatius** [comment]
Still shows the same size for me:

image

@javimendezona 

Not sure what the reason is...

**Comment by Scrum** [comment]
@javimendezona There is still no link to `github repository`

**Review by devdreamsolution — APPROVED** [review]

**Pull request closed without merging**
