### PR TITLE
Added Font Awesome Icon Finder to Dev Tools list

### PR DESCRIPTION
**Pull request by CS76**

### CODE REVIEW

**Comment by DannyFeliz** [comment]
Awesome man, very useful

**Comment by CS76** [comment]
Glad, it was helpful. Let me know if you have any suggestions and also please feel free to share it :)

**Comment by DannyFeliz** [comment]
Yeah, I shared it with my co-workers in a Slack channel

**Comment by CS76** [comment]
Here is the repo link https://github.com/CS76/fontawesome-icon-finder
In specific

The extension is powered by VueJS, using its runtime-only build (fully CSP-compliant). 

This [VueJS single file component](https://github.com/CS76/fontawesome-icon-finder/blob/master/vue-fontawesome/src/App.vue) is being precompiled into render functions using the runtime-only build with Webpack + vue-loader and then used for developing the chrome extension component.

Let me know if you need more details. 

Thanks

**Comment by CS76** [comment]
@kazupon Any update on this ??

**Comment by CS76** [comment]
@kazupon Thank you (y)

**Pull request merged**
