### PR TITLE
Add vue-pano

### PR DESCRIPTION
**Pull request by ChiChou**
[vue-pano](https://github.com/ChiChou/vue-pano) is a vue based component for displaying interactive panorama images

### CODE REVIEW

**Comment by ChiChou** [comment]
@kazupon 
Of course it has English doc. Jut forgot to link that in the home page.
https://github.com/ChiChou/vue-pano/blob/master/README.en.md

**Comment by kazupon** [comment]
Thanks!

However, we hope it's the default dry to English is global standard.

**Comment by ChiChou** [comment]
All done.

**Comment by kazupon** [comment]
thanks!

**Pull request merged**
