### PR TITLE
Add script to update repository stars

### PR DESCRIPTION
**Pull request by michaelmior**
I noticed the star counts on several of the repositories were outdated, sometimes by quite a lot. Since it's helpful to have these and a pain to update them all manually, I wrote a small script that parses the README and uses the GitHub API to fetch the new count and update. To use the script you just need to define the `GITHUB_USERNAME` and `GITHUB_TOKEN` environment variables.

I made the text bold if the repository has more than 100 stars since that seemed to roughly the threshold which was already used.

### CODE REVIEW

**Comment by michaelmior** [comment]
Ah, I didn't realize there was a bot for this. Normally I would ping repo maintainers before building something like this, but I was having fun so I decided to go for it anyway :)

**Comment by angleman** [comment]
Until the awesome-lists-bot is going you can view [README_STARS.md](https://github.com/angleman/awesome-vue/blob/master/README_STARS.md). Note sometimes the shields.io images don't load and you need to refresh your browser.

**Comment by michaelmior** [comment]
Thanks!

**Comment by angleman** [comment]
@kazupon, is there an ETA on the awesome-lists-bot solution?

**Pull request closed without merging**
