### PR TITLE
Add FactorJS 

### PR DESCRIPTION
**Pull request by arpowers**
Adding FactorJS under SSR frameworks.

### CODE REVIEW

**Comment by arpowers** [comment]
@Scrum all set !

**Comment by arpowers** [comment]
@Scrum can you explain to me what's happening here? Can't find any issues

**Comment by Scrum** [comment]
@arpowers Your commit consists of adding an empty line, most likely when resolving the conflict you lost the addition of a nice package

**Comment by arpowers** [comment]
@Scrum I can see Factor on the repo, so I think this got pulled in twice? Anyway, this can be closed.

**Pull request closed without merging**
