### PR TITLE
Move to Vue Community and AwesomeJS

### PR DESCRIPTION
**Pull request by Akryum**
While thanking everyone contributing (thank you so much :pray:), we feel it's difficult to maintain this repository and it has duplicate content from both [Vue Community](https://vue-community.org/) and [awesomejs.dev](https://awesomejs.dev/for/vue/) as we discussed [here](https://github.com/vuejs/awesome-vue/issues/3080).

As a result I think it would be better for the community to focus our efforts on those two projects that present the information in a more organized way than a simple Readme file. don't get me wrong, it is an awesome resource and the contributors have put a lot of time into it (thank you again for all your contributions), but I feel it's time to move on and improve Vue community and AwesomeJS instead.

In this PR I've made a tentative revamp of the readme that will help redirect people to the right place by presenting Vue Community and AwesomeJS with a handful of shortcut links.

It's rendered [here](https://github.com/vuejs/awesome-vue/tree/refactor).

Please don't hesitate to give feedback here! 😸

### CODE REVIEW

**Comment by Scrum** [comment]
I fully support moving forward to more convenient ways to get information, but I think this PR is a bit of a coordinate because many people need time to adjust to the new.

I would suggest leaving your PR in a prominent place, but do not delete the content until a certain time

**Comment by Jogai** [comment]
I dont agree that awesomejs is a better format than the current readme file. In fact, it looks like its riding the popularity of the awesome lists (as @sindresorhus made and build a community around) and competes with it.

**Comment by altitudems** [comment]
I think this is the right thing to do. I have been a Vue user since before there was an Awesome list, and I can tell you first hand, that the readme file format has become very unreliable, hard to use, and impossible to navigate quickly. As useful as it has been, Vue and its ecosystem has just evolved. Credit to all those who put work into making this what it is, but time to move on.

**Comment by Christoph-Wagner** [comment]
I’d want to throw another vote against awesomejs. I just saw the site for the first time, and my impression was of some kind of mobile emulator. But I’m on a desktop. The site wastes an insane amount of space, I realize many people surf on mobile nowadays, but this is one of many examples of going too far and doing mobile-almost-exclusively instead of mobile-first.

When I go to the readme here and click ui-components, I get 27 projects and their detailed description on my FullHD screen. On awesomejs, I get 7 and a fraction of their description. That’s so much worse, it’s not even funny.

I agree and understand that with growth the readme.md format becomes a horror to maintain and keep up to date. But telling people to use awesomejs instead is a giant step backwards.

**Review by devdreamsolution — APPROVED** [review]

**Review by devdreamsolution — APPROVED** [review]

**Comment by Scrum** [comment]
Quite a long time passed and the reactions of the society were not agitated by this proposal.

**Pull request closed without merging**
