### PR TITLE
add [notifications] - vue-snotify

### PR DESCRIPTION
**Pull request by artemsky**
https://github.com/artemsky/vue-snotify - Vue.js 2 Notification Center

### CODE REVIEW

**Comment by NxtChg** [comment]
Did you really name your component "snotty-fi"? :)

**Comment by artemsky** [comment]
Oh man, I didn't think about that meaning. 🤣 
The idea was like "smart notifications", or "smart notify", but it's too complicated, so I decided to shorten it to "snotify"

**Comment by NxtChg** [comment]
Yeah, things like that happen :)

**Comment by NxtChg** [comment]
I came close too, by the way, mine is vs-notify.

**Comment by artemsky** [comment]
I had no chance to rename it) because of my angular version already works. I just ported it to vuejs -
 https://github.com/artemsky/ng-snotify

**Comment by NxtChg** [comment]
It's not a big deal, someone might chuckle but he will understand :)

**Comment by ankurk91** [comment]
@artemsky
Thanks for making this.
One of the best notification package so far.

**Pull request merged**
