### PR TITLE
Add ui components jsmod-vue-pc

### PR DESCRIPTION
**Pull request by chaogao**
jsmod-vue-pc is highly scalable ui components ,  designed for the client side interface.

### CODE REVIEW

**Comment by chaogao** [comment]
@kazupon thank you 

ok, but need to wait a few days

**Comment by kazupon** [comment]
@chaogao 
no problem 👍

**Comment by chaogao** [comment]
hi @kazupon i wrote document and website in both Chinese and English ~

**Comment by kazupon** [comment]
Thanks!

**Pull request merged**
