### PR TITLE
Laravel Spark - Page Not Found

### PR DESCRIPTION
**Pull request by ivory4491**

### CODE REVIEW

**Comment by yyx990803** [comment]
Instead of removing it, we should just remove the link and keep the entry.

**Comment by kayyyy** [comment]
I dont think Spark will be for free / Open Source for the public: https://twitter.com/taylorotwell/status/717132746276077568

**Comment by azamat-sharapov** [comment]
Maybe just place this link: https://spark.laravel.com

**Comment by yyx990803** [comment]
Already updated.

**Pull request closed without merging**
