### PR TITLE
Added Mevn-CLI to the scaffolding tools list

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Mevn-CLI is much more than a scaffolding tool as it automates the entire local environment workflow making Developers more productive.

Docs: https://mevn.madhacks.co
Featured within https://bestofjs.org/projects/mevn-cli

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@kazupon Thoughts :thinking:

**Comment by jamesgeorge007** [comment]
cc @kazupon

**Comment by jamesgeorge007** [comment]
cc @kazupon @yyx990803

**Comment by DannyFeliz** [comment]
@jamesgeorge007 Relax, do not despair @kazupon will merge your changes sooner or later, you're not the only one there are others 63 PR waiting. BTW Evan does not maintain this repo 😋.

**Pull request merged**
