### PR TITLE
refactor Awesome Vue #836

### PR DESCRIPTION
**Pull request by brillout**

### CODE REVIEW

**Comment by brillout** [comment]
@Ffloriel 👍, also for adding conditions to the contrib file. I'll add some for libraries after this PR is merged.

**Comment by kazupon** [comment]
Update done.
Please check it.

**Comment by znck** [comment]
@kazupon How about merging this?

**Comment by kazupon** [comment]
@znck I'll merge like this. :)

**Comment by jcc** [comment]
@kazupon I find some packages were deleted in the pull request.

Example: 
[v-dispicker](https://github.com/jcc/v-distpicker) [V-Distpicker](https://github.com/jcc/v-distpicker) - A flexible, highly available district selector for picking provinces, cities and districts of China. by [Jiajian Chan](https://github.com/jcc)
[vue-emoji](https://github.com/rishiqing/vue-emoji): An emoji component based on vue.js 2.x By [@374632897](https://github.com/374632897)

**Comment by znck** [comment]
@jcc This PR was a major refactor with too many changes. If we missed or accidentally deleted something, please send a PR.

**Comment by posva** [comment]
If your repo got deleted, make sure to check the reason first at https://github.com/brillout/awesome-vue/blob/master/README.md

**Comment by jcc** [comment]
@posva Thx, I understand.

**Pull request merged**
