### PR TITLE
add vuex-local-state

### PR DESCRIPTION
**Pull request by biluochun**
add vuex-local-state

### CODE REVIEW

**Comment by nickmessing** [comment]
@kazupon, it was at the end of the list already, now it's just in the wrong category.

**Comment by biluochun** [comment]
I updated the document in English.. ^_^ ..

**Comment by nickmessing** [comment]
@biluochun, can you please revert last commit? (move it back to the end of Vuex Utilities)

**Comment by nickmessing** [comment]
@kazupon, any objections?

**Pull request merged**
