### PR TITLE
add open source

### PR DESCRIPTION
**Pull request by ericjjj**

### CODE REVIEW

**Comment by brillout** [comment]
@kazupon thanks for the ping and agree. Also, @Ffloriel was in charge of the Projects section in the refactor. @Ffloriel what do you think?

> ericjjj/douban

The first note `1. xxx` is not helpful. Things added to Awesome Vue should have a minimum of quality. Otherwise the list is not awesome anymore:).

Also, if the website is deployed, then a link to the website would be nice.

> ericjjj/pm86 
> ericjjj/vms

Can't say much about these two since the doc is not in English

**Comment by Ffloriel** [comment]
hey @brillout, so I think 

> Open Source section gives the possibility for developers to contribute and be a part of an opensource project using their knowledge of the vuejs.

For that reason, it is important that the readme is in English and is understandable.
I don't have the impression that those projects are still in development and in search of contributors.

> If you consider your project finished, and it does not need any contributions, consider the apps/website category.

I tried to access the websites (_vms_ and _pm86_) but I encountered error messages like this one:

> Error: Request failed with status code 400
> Error: Request failed with status code 403

_douban_ does not have a link to a demo website or screenshot of the application.

I think open source projects that are now over and does not have a great website can still have a great value as an example.  
 If the code is well written and the technologies are used properly, it can be useful to some people as an example.  
I saw two projects called _douban_ in the Example section that are probably related.

**Comment by ericjjj** [comment]
Add english document,
Move to open source section,
😀

**Comment by ericjjj** [comment]
@kazupon

**Comment by kazupon** [comment]
@ericjjj 
Thanks.
I checked your projects.
I think readme should be in english with default.

**Comment by ericjjj** [comment]
@kazupon thanks , I have modified the readme

**Pull request merged**
