### PR TITLE
重新提交音乐组件

### PR DESCRIPTION
**Pull request by petsgre**
本次提交新增了 readme.md
添加了组件所需要的背景图片，等等。

### CODE REVIEW

**Comment by Nowforpasserby** [comment]
？？？？？？

**Comment by petsgre** [comment]
!!

**Comment by petsgre** [comment]
How do I resolve conflict?Can't click the button called conflict resolution!

**Comment by petsgre** [comment]
These conflicts are too complex to resolve in the web editor????

**Pull request closed without merging**
