### PR TITLE
Dead site link moved to the github example

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by Piterden** [comment]
Actually, project is finished, and had be abandoned. But on github it could help young programmers. Plus it is the only app, which I saw, with russian comments.

**Comment by Fl0pZz** [comment]
I'm the Russian programmer, and I absolutely agreed)

**Comment by nickmessing** [comment]
@kazupon, as a russian speaker I can confirm that site is abandoned and github could be useful indeed.

**Comment by kazupon** [comment]
@nickmessing okay, got it.

**Pull request merged**
