### PR TITLE
Added Vue.Isotope

### PR DESCRIPTION
**Pull request by David-Desmaisons**
Added Vue.Isotope.

### CODE REVIEW

**Comment by QWp6t** [comment]
4 commits to add one line to a readme? That's fantastic. :joy:

**Comment by David-Desmaisons** [comment]
@QWp6t  It is because it´s from a branch I created for another pull request, and resynchronized with master repo

**Comment by kazupon** [comment]
@David-Desmaisons 
Thank you for your PR.

We need to maintain the commits logs cleanly.
Can you squash the commit histories ?

**Comment by miljan-aleksic** [comment]
@kazupon, you can choose to squash the commits when merging the Pull Request. It's relatively new feature that can be enabled in the repo settings.

**Comment by kazupon** [comment]
@miljan-aleksic 
Oh, That reminds me 😝

**Comment by David-Desmaisons** [comment]
@miljan-aleksic , @kazupon Thanks!!

**Pull request merged**
