### PR TITLE
feat(frameworks): Anu added in frameworks

### PR DESCRIPTION
**Pull request by jd-solanki**
- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [x] Link description does not contain a link to an author / third-party resource
- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

#### `Apps/Websites`

- [x] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [x] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [x] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

### CODE REVIEW

**Comment by Jogai** [comment]
Since you're using antfu's stuff already, maybe add https://github.com/antfu/unplugin-icons for importing the icons

**Comment by jd-solanki** [comment]
> Since you're using antfu's stuff already, maybe add [antfu/unplugin-icons](https://github.com/antfu/unplugin-icons) for importing the icons

In my lib or in this repo?

**Comment by Jogai** [comment]
I meant your repo, but yeah, this repo could use some antfu projects ;)

**Comment by jd-solanki** [comment]
> I meant your repo, but yeah, this repo could use some antfu projects ;)

Thanks for the suggestion but [Anu](https://github.com/jd-solanki/anu#features-) is already using [UnoCSS](https://github.com/unocss/unocss) which provides pure CSS icons. How `unplugin-icons` will benefit from this.

Thanks.

**Comment by Jogai** [comment]
You still need to import a certain collection, with unplugin this could be automatic per icon: https://github.com/antfu/unplugin-icons#auto-importing

**Comment by jd-solanki** [comment]
> You still need to import a certain collection

No, You just install the lib you want e.g. If I want mdi icons in my lib then all I have to do is install the lib via:

```shell
pnpm add -D @iconify-json/mdi
```

later on I can just use class:

```html
<div class="i-mdi-alarm text-orange-400" />
```

No imports at all 🤷🏻‍♂️

**Comment by Jogai** [comment]
I meant install. With autoimporting you can even skip that step

**Pull request merged**
