### PR TITLE
update(docs): added Awesome Vue Boilerplate in Scafold section

### PR DESCRIPTION
**Pull request by NarHakobyan**
added Awesome Vue Boilerplate in Scafold section and fixed indents

### CODE REVIEW

**Comment by NarHakobyan** [comment]
@kazupon There are not correct, look at the indent of subs Resources section

**Comment by kazupon** [comment]
If so, you need to match the `UI Components` section and other indexes as well.
IMO, I think `Resources` section should be adjusted the indent.

**Comment by NarHakobyan** [comment]
@kazupon I have fixed it :)

**Comment by kazupon** [comment]
Thanks!

**Pull request merged**
