### PR TITLE
Add vue-relay

### PR DESCRIPTION
**Pull request by ntkme**
Adding [vue-relay](https://github.com/ntkme/vue-relay).

### CODE REVIEW

**Comment by ntkme** [comment]
Done! Sorry that I did not notice it in the first place.

**Comment by kazupon** [comment]
@ntkme 
Thanks! 🙏 

In addition, due to it is realized with GraphQL, I think that it should be categorized `GraphQL` rather than `Relay`.

**Comment by ntkme** [comment]
We don't have a dedicated GraphQL category yet. I see `vue-apollo` is under "Integrations" category. Shall I create a GraphQL category and move it around then?

**Comment by kazupon** [comment]
Sorry for my late reply.

You can put it as subcategory under `Utilities`.

>Shall I create a GraphQL category and move it around then?

Yes, You can it too. :)

**Comment by ntkme** [comment]
@kazupon Done.

**Pull request merged**
