### PR TITLE
Add new pomotroid fork

### PR DESCRIPTION
**Pull request by kdaghari**

### CODE REVIEW

**Comment by Splode** [comment]
[Pomotroid](https://github.com/splode/pomotroid) is actively developed and maintained. @kdaghari perhaps change the name of your fork to avoid duplication and confusion?

**Comment by Scrum** [comment]
I'm not sure that it makes sense to keep the same entities named differently

**Comment by LinusBorg** [comment]
The author can send a new PR with his fork appropriately named and documented

**Comment by karimdxy** [comment]
@Splode, at the time there wasn't really much going on (besides the bot updating deps) so I thought it was dead. I had no intention to hijack the name or whatever.

@Scrum, you're right.

**Pull request closed without merging**
