### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by techicsdev**
an ecommerce website with laravel and vuejs

### CODE REVIEW

**Comment by Jogai** [comment]
Link is dead?

**Comment by Jogai** [comment]
Not really, it looks like the whole domain has no dns records.

**Comment by Jogai** [comment]
Maybe learn a bit more about redirects etc. http://www.mumbasket.com/ does answer, but with a white page, and https://mumbasket.com/ does nothing.
https://serverfault.com/questions/446674/how-to-configure-nginx-to-redirect-all-request-from-domain-aliases-to-main-domai/446731

**Comment by techicsdev** [comment]
can you please check now?? it's working file

**Pull request merged**
