### PR TITLE
Testing section

### PR DESCRIPTION
**Pull request by TheJaredWilcurt**
* Moved VTU to top. since it is official.
* Added Jest-Serializer-Vue-TJW
* vuenit and vue-unit are both VTU alternatives that haven't been updated since VTU came out. Moved more interesting projects above them.
* vue-container is no longer maintained, moved to bottom

### CODE REVIEW

**Comment by TheJaredWilcurt** [comment]
@Scrum Merge conflict is resolved. This PR includes organizing this sections so the most relevant projects are moved to the top, and the deprecated/unmaintained are moved to the bottom.

**Comment by Scrum** [comment]
> Always add your items to the end of a list. To be fair, the order is first-come-first-serve.

see [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md)

We do not single out anyone, everyone is equal here. Please return the list to its original state and add yours link to the end of the list

**Comment by TheJaredWilcurt** [comment]
I understand your reasoning behind why this rule exists generally, to prevent people from doing self-promotion. However it leads to a disorganized mess. You might as well just do it alphabetically so people do not infer meaning from the order. Or, better, actually order them meaningfully, to save people time. Though this ordering takes the time of those maintaining the list, which is what I was trying to help with.

**Comment by Scrum** [comment]
@TheJaredWilcurt I didn’t immediately notice that you made the correction on another line, regarding this as adding your package

**Comment by Scrum** [comment]
> I understand your reasoning behind why this rule exists generally, to prevent people from doing self-promotion. However it leads to a disorganized mess. You might as well just do it alphabetically so people do not infer meaning from the order. Or, better, actually order them meaningfully, to save people time. Though this ordering takes the time of those maintaining the list, which is what I was trying to help with.

There are rules, they must be observed otherwise there will be chaos. Putting order in the lists should be done as a separate task without mixing with the addition of

**Pull request merged**
