### PR TITLE
Added charliekassel/vuejs-datepicker to the UI Components section

### PR DESCRIPTION
**Pull request by kkomelin**

### CODE REVIEW

**Comment by kazupon** [comment]
sorry,
can you resolve conflict please ?

**Comment by kkomelin** [comment]
Hey @kazupon. I'll try

**Comment by kkomelin** [comment]
@kazupon Done. Please review.

**Comment by kazupon** [comment]
Thanks!!

**Comment by kkomelin** [comment]
Thanks @kazupon for reviewing and merging my PR. A separate thanks for the awesome list of Vue resources ;)

**Pull request merged**
