### PR TITLE
Added iviewui.

### PR DESCRIPTION
**Pull request by lbogdan**

### CODE REVIEW

**Comment by nickmessing** [comment]
There's already a PR for that - #1310.

**Comment by lbogdan** [comment]
@nickmessing Yeah, saw that after the fact, sorry. Also saw that it needed changes, so I left this one, too. :smile:

**Comment by nickmessing** [comment]
@lbogdan, as our rules say - first come - first serve :smile:, I'll update it for him.

**Comment by lbogdan** [comment]
Sure thing! :+1:

**Pull request closed without merging**
