### PR TITLE
Counting stars.

### PR DESCRIPTION
**Pull request by abrahamgreyson**

### CODE REVIEW

**Comment by DannyFeliz** [comment]
you used the API or did hand?

**Comment by abrahamgreyson** [comment]
@DannyFeliz I did this with my bare hand, build use script is better way but I'm newbie to JS.

**Comment by kazupon** [comment]
@vuejs/collaborators 
I think that we should be updated star count with the build script.

IMO, a best way, to automatically update star count with GitHub API in CircleCI/TravisCI when the PR merged.

**Comment by phanan** [comment]
> IMO, a best way, to automatically update star count with GitHub API in CircleCI/TravisCI when the PR merged.

Totally agree. 
Btw, why are some resource names in bold and the others not?

**Comment by phanan** [comment]
Wait. Doesn't that also mean the star counts will remain unchanged as long as there's no PR?

**Comment by qiansen1386** [comment]
@phanan If you want to make it even more up-to-date, there has to be a daily-building system or sort. But, I believe, triggering by commits should be good enough. We have several new PRs for every week in this month.

**Comment by shentao** [comment]
Strongly agree!

**Comment by azamat-sharapov** [comment]
https://github.com/vuejs/awesome-vue/pull/179#issuecomment-214583539
https://github.com/vuejs/awesome-vue/pull/176

**Comment by abrahamgreyson** [comment]
@azamat-sharapov Thanks, the bot looks like inactive for weeks.
https://github.com/awesome-lists-bot?tab=activity

**Comment by mrgodhani** [comment]
Does the list get updated often ? For example https://github.com/mrgodhani/rss-reader RSS Reader now has 191 stars.

**Comment by kazupon** [comment]
Close (resolve with @awesome-lists-bot)

**Comment by abrahamgreyson** [comment]
@kazupon :kiss:

**Pull request closed without merging**
