### PR TITLE
Add SimpleNexus to commercial products

### PR DESCRIPTION
**Pull request by catskull**
We've been using Vue for about 2 years now and totally love it!

Most of our vue stuff is behind a login page, but the login page itself uses vue and shows up in the vue devtools detects it: https://simplenexus.com/login

### CODE REVIEW

**Comment by kazupon** [comment]
I cannot access login page due to unauthorized ...

**Comment by catskull** [comment]
@kazupon Sorry! Our product is strictly US only so we don't allow access outside the US. If this is a problem for this list, feel free to close this PR.

**Comment by kazupon** [comment]
Closing due to inactivity. 
Please open a new issue with a reference to this one if you can follow up with more information.

**Comment by catskull** [comment]
I explained why the login page was unauthorized. Is worldwide access required for this list?

**Pull request closed without merging**
