### PR TITLE
add vue-cli

### PR DESCRIPTION
**Pull request by rodzzlessa24**

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks, it is already listed: https://github.com/vuejs/awesome-vue#scaffolding

**Comment by rodzzlessa24** [comment]
This is a different vue-cli

**Comment by yyx990803** [comment]
Ah sorry, but would you mind renaming your project to differentiate the two? I think it could be confusing for users...

**Comment by rodzzlessa24** [comment]
No problem would a simple vue-cli-tool rename be enough or should I rename it completely?

**Comment by yyx990803** [comment]
I'd prefer something more different, because a `vue-cli` prefix still looks the two are related. How about `vue-go-cli` or `vue-scaffold`?

**Pull request closed without merging**
