### PR TITLE
add new component about audio.   please~~~

### PR DESCRIPTION
**Pull request by forijk**
add one new component about audio.   please~~~

---Modified README.md

### CODE REVIEW

**Comment by DannyFeliz** [comment]
@forijk I created a PR fixing a typo and improving the syntax highlighting  https://github.com/forijk/vue-audio-better/pull/2

**Comment by forijk** [comment]
@DannyFeliz Thank you~

**Comment by forijk** [comment]
git: pull request template structure not broken

**Comment by forijk** [comment]
@Scrum git: pull request template structure not broken

**Comment by Scrum** [comment]
@forijk You have deleted the PR template, please read carefully https://github.com/vuejs/awesome-vue/blob/master/.github/pull_request_template.md

**Comment by forijk** [comment]
### `General`
> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

#### `Apps/Websites`

- [x] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [x] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [x] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [x] A commercial product using Vue, provided that guests could reasonably check out how Vue was used A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

**Comment by forijk** [comment]
@Scrum 
Sorry, I didn't know this before. I have submitted it according to the template~

**Comment by Scrum** [comment]
@forijk You checked all the points. I don’t understand what category you assigned your package to.

**Comment by forijk** [comment]
@Scrum 
Sorry, the template has been updated, is it ok?
Thank you!

**Pull request merged**
