### PR TITLE
Greenpress - open-source platform

### PR DESCRIPTION
**Pull request by davidmeirlevy**
- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
of course not, it's a wordpress-alternative built for the 21st century, so the code is separated to micro-services.
2 of those services are vue applciations (admin panel built with vue and element-ui, and the blog front with Nuxt for the SSR).

**Comment by davidmeirlevy** [comment]
BTW, both are using the composition API and every latest update of vue to make an example.

**Comment by davidmeirlevy** [comment]
Changed made.

just to make you interested, this is a demo running blog using greenpress on heroku:
https://greenpress.herokuapp.com/

and this is my own blog, using the platform (on heroku too, hobby package):
https://www.davidlevy.co.il/

This platform can run on apache web hosting packages, cloud services, docker, kubernetes, etc,and also provided with multi-tenancy so you can manage several websites on the same server and databases.

**Comment by Scrum** [comment]
> Changed made.
> 
> just to make you interested, this is a demo running blog using greenpress on heroku:
> https://greenpress.herokuapp.com/
> 
> and this is my own blog, using the platform (on heroku too, hobby package):
> https://www.davidlevy.co.il/
> 
> This platform can run on apache web hosting packages, cloud services, docker, kubernetes, etc,and also provided with multi-tenancy so you can manage several websites on the same server and databases.

Thank you, I don’t think I can devote enough time to this.

**Comment by davidmeirlevy** [comment]
> Thank you, I don’t think I can devote enough time to this.

if you ever think about creating a blog, and you wish to have a fully-system like Wordpress, with admin panel and so, so use Greenpress instead. It's really easy to install and run.

Thanks!

**Pull request merged**
