### PR TITLE
Add Vue Material

### PR DESCRIPTION
**Pull request by marcosmoura**
**[Vue Material](https://marcosmoura.github.io/vue-material/)**
Material Design for Vue.js. Lightweight components built from scratch exactly according to the specs.

### CODE REVIEW

**Comment by LinusBorg** [comment]
Wow, these look awesome! Thanks!

**Comment by marcosmoura** [comment]
It is a silly question, but what do you think about this project and his components? I've released it today and I'm really exciting to hear some feedbacks about it.

**Comment by LinusBorg** [comment]
Not a silly question at all. 

I just clicked through all the examples, and clicked everywhere :D They look and feel great!

A bit more documentation besides the code examples would be helpful.

Generally, I want to use them but have no real experience with material design principles, so I'm a fraid that I might have a hard time to build a harmonious design around these. (grid, spacing, positioning, tables ...) But thatis probably my personal problem.

**Comment by marcosmoura** [comment]
Oh. Great to hear that. It's on my roadmap to detail better the API and give some codepen examples. Like a playground. I think that this would probably make this easier to reason about.
But your feedback will help me a lot. Thank you!

**Comment by DannyFeliz** [comment]
I love this, I clicked in every example and tested it.

Thanks @marcosmoura

**Pull request merged**
