### PR TITLE
add: vue-restricted-input

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by Scrum** [comment]
@awesome-vue/collaborators ping

**Comment by Scrum** [comment]
@kazupon done

**Comment by Scrum** [comment]
@kazupon ping

**Comment by Scrum** [comment]
@kazupon ping ?

**Comment by Scrum** [comment]
@kazupon ping

**Comment by Scrum** [comment]
@kazupon @yyx990803 @sdras @shentao @Akryum @posva 

Good day, wherever you are, I draw your attention as This PR was not considered for a very long time despite my attempts to ping in this problem and the written appeal to @kazupon  which I wrote a week ago and to which I was never given an answer.

If you don’t have enough time for this repository, I can start maintaining it, because for some it can be very important.

Thank you for understanding.

**Comment by Scrum** [comment]
@LinusBorg ping ?

**Comment by Scrum** [comment]
@LinusBorg Hi, I would like to help this repository, what can I do for this?

**Comment by DannyFeliz** [comment]
@LinusBorg same as @Scrum I can help maintaining this repository too.

**Comment by ajtruex** [comment]
@LinusBorg I'd also like to volunteer to help maintain this repo as @Scrum and @DannyFeliz previously suggested.

Let me know if there is anything I can do to help.

**Pull request merged**
