### PR TITLE
Adding misc. resources

### PR DESCRIPTION
**Pull request by ackzell**
These are things I have been working on. 
The podcast is alongside a really good friend and some episodes with a special guest that almost turned into a full time host.

- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [ ] Link description does not contain a link to an author / third-party resource
- [ ] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [ ] The documentation is in English.
- [ ] The project is active and maintained.
- [ ] The project accepts contributions.
- [ ] Not a commercial product

#### `Apps/Websites`

- [ ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [ ] The website is using vuejs intensively. It should detect vue with [vue-devtools](https://github.com/vuejs/vue-devtools).
  > If you cannot detect vue with `vue-devtools` due to work at non public pages (e.g. for enterprise website), you can send Pull Request with screenshot that detected it.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vue, provided that guests could reasonably check out how Vue was used (i.e. A headless CMS which uses Vue for the Admin/editor Area and offers a free tier).

### CODE REVIEW

**Review by Scrum — CHANGES_REQUESTED** [review]
Please change the title to English

**Comment by ackzell** [comment]
Hi @Scrum, thanks for your review.
What title is it that needs to be in English? The PR title is "Adding misc. resources".

Do you mean the title for the podcast episodes? The content is in Spanish, so the episodes titles are in Spanish but I'd be happy to translate them. Same goes for the Scrimba course.

**Comment by Scrum** [comment]
> Hi @Scrum, thanks for your review. What title is it that needs to be in English? The PR title is "Adding misc. resources".
> 
> Do you mean the title for the podcast episodes? The content is in Spanish, so the episodes titles are in Spanish but I'd be happy to translate them. Same goes for the Scrimba course.

I'm talking about headlines

- [¿Qué es Pinia? con @posva]
- [Evolución de Vue - Parte I]
- [React vs Vue - las comunidades

**Comment by ackzell** [comment]
Thanks for the clarification @Scrum. 

I made the requested changes.

**Review by Scrum — APPROVED** [review]

**Comment by anHaoRan** [comment]
这是来自QQ邮箱的自动回复邮件。您发的邮件我已收到

**Pull request merged**
